todo_app/config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

todo_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

todo_app/app/models/todo.rb
class Todo < ApplicationRecord
end

todo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

todo_app/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end
  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(params[:todo])
    @todo.save
    redirect_to todos_path
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

todo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

todo_app/app/helpers/todos_helper.rb
module TodosHelper
end

todo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

todo_app/app/views/todos/index.html.erb
<h1>Listado de Tareas</h1>
<h3>Crear una nueva Tarea: <a href="<%= todos_new_path%>">aqui</a></h3>
<div class="row">
  <div class="well">
    <p><%= @todos %></p>
  </div>
</div>

todo_app/app/views/todos/new.html.erb
<%= form_with model: @todos, local:true do |f| %>
  <%= f.label :description, "Tarea"%>
  <%= f.text_field :description%>

  <%= f.label :completed, "CheckBox"%>
  <%= f.check_box :completed%>

  <%= f.submit "Enviar" %>
<%end%>